"""
Author: Kelvin Gooding
Created: 2023-10-19
Updated: 2024-02-22
Version: 1.1
"""

# Modules

from modules import smtp_mail
from modules import auth
import time
import socket
import os

# Variables

result = os.popen('hostname -I').read()

# Script

smtp_mail.send_email('kelv.gooding@outlook.com', f"[{socket.gethostname()} - {result.split()[0]}] - This server is now online", 'This is an automated message generated by our server to provide you with important information or updates. Please note that this email is sent automatically and is not monitored for replies.')
