---
# tasks file for reboot
#
- name: "OS - Reboot Ubuntu nodes - {{ current_time }}"
  reboot:
  when: ansible_distribution == "Ubuntu"

- name: "OS - Reboot RHEL nodes - {{ current_time }}"
  reboot: 
  when: ansible_distribution == "RedHat"

