---

- name: vm_snowmoon_dev - Server setup & configuration
  hosts: vm-snowmoon-dev
  become: true
  vars:
    ubuntu_packages:
      - git
      - network-manager
      - openssh-client
      - openssh-server
      - python3
      - python3-pip
      - sshpass
      - zip
      - net-tools
    rhel_packages:
      - git
      - python3
      - python3-pip
      - sshpass
      - zip
      - net-tools
    pip_packages:
      - flask
      - pip==22.3.1 
    dir_names:
      - "/home/{{ ansible_user }}/apps"
      - "/home/{{ ansible_user }}/.ssh"
  roles:
    - linux_network_connectivity
    - linux_update
    - linux_package_install
    - linux_create_dirs
    - linux_user_permissions
    - network_dns_update
    - pip_package_install
