---

- name: vm_snowmoon - Server setup & configuration
  hosts: vm-snowmoon
  become: true
  vars:
    ubuntu_packages:
      - git
      - network-manager
      - openssh-client
      - openssh-server
      - python3
      - python3-pip
      - sshpass
      - zip
      - net-tools
    rhel_packages:
      - git
      - python3
      - python3-pip
      - sshpass
      - zip
      - net-tools
    pip_packages:
      - flask
      - pip==22.3.1
    dir_names:
      - "/home/{{ ansible_user }}/.ssh"
    port_numbers:
      - 3000
      - 3001
      - 3002
      - 3003
      - 3004
      - 3005
      - 3006
      - 3007
  roles:
    - linux_network_connectivity
    - linux_update
    - linux_package_install
    - linux_create_dirs
    - linux_user_permissions
    - network_dns_update
    - pip_package_install
    - linux_firewall_allow
