---

- name: Installing Linux packages 
  hosts: localhost
  become: true
  vars:
    ubuntu_packages:
      - ansible
      - docker.io
      - git
      - network-manager
      - openssh-client
      - openssh-server
      - python3
      - python3-pip
      - sshpass
      - zip
    rhel_packages:
      - ansible
      - docker.io
      - git
      - network-manager
      - openssh-client
      - openssh-server
      - python3
      - python3-pip
      - sshpass
      - zip
  roles:
    - linux_network_connectivity
    - linux_package_install
